version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: queuecommerce-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - queuecommerce-network

volumes:
  rabbitmq_data:

networks:
  queuecommerce-network:
    driver: bridge
