version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: buzzmail-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - buzzmail-network

  mongodb:
    image: mongo:7.0
    container_name: buzzmail-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: buzzmail-orders
    volumes:
      - mongodb_data:/data/db
    networks:
      - buzzmail-network

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  buzzmail-network:
    driver: bridge
